# Generated by Django 2.0.1 on 2018-01-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireserv', '0003_auto_20180126_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='account',
            name='county',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='account',
            name='province',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
