# Generated by Django 2.0.1 on 2018-02-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireserv', '0007_auto_20180209_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='inquiry_id',
            field=models.IntegerField(default=0),
        ),
    ]
