# Generated by Django 2.0.1 on 2018-02-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireserv', '0009_auto_20180222_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='subtypea1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='subtypea2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='subtypea3',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='subtypeb1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='subtypeb2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='subtypeb3',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='subtypec1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='subtypec2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='subtypec3',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='subtyped1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='subtyped2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='subtyped3',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='subtypee1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='subtypee2',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
