# Generated by Django 2.0.1 on 2018-02-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireserv', '0010_auto_20180225_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
