# Generated by Django 2.0.1 on 2018-03-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireserv', '0015_auto_20180310_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acct_id', models.IntegerField(default=-1)),
                ('fire_code', models.CharField(default='000000', max_length=10)),
                ('fire_points', models.PositiveIntegerField(default=0)),
                ('commission_rate', models.PositiveIntegerField(default=0)),
                ('t_sales', models.PositiveIntegerField(default=0)),
                ('y_sales', models.PositiveIntegerField(default=0)),
                ('m_sales', models.PositiveIntegerField(default=0)),
                ('t_commission', models.PositiveIntegerField(default=0)),
                ('y_commission', models.PositiveIntegerField(default=0)),
                ('m_commission', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=0)),
                ('stars', models.PositiveIntegerField(default=0)),
                ('t_bonus', models.PositiveIntegerField(default=0)),
                ('y_bonus', models.PositiveIntegerField(default=0)),
                ('m_bonus', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
