# Generated by Django 2.0.1 on 2018-03-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireserv', '0017_agent_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acct_id', models.IntegerField(default=-1)),
                ('order_id', models.CharField(max_length=20)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_delivered', models.DateTimeField(blank=True)),
                ('time_resolved', models.DateTimeField(blank=True)),
                ('product_total', models.PositiveIntegerField(default=0)),
                ('delivery_fee', models.PositiveIntegerField(default=0)),
                ('final_payment', models.PositiveIntegerField(default=0)),
                ('num_of_products', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='PLACED', max_length=10)),
                ('fire_code', models.CharField(default='000000', max_length=10)),
                ('cus_name', models.CharField(blank=True, default='', max_length=20)),
                ('cus_phone', models.CharField(blank=True, default='', max_length=20)),
                ('cus_address', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
    ]
