# Generated by Django 2.0.1 on 2018-03-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireserv', '0018_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_delivered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_resolved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
