# Generated by Django 2.0.1 on 2018-03-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireserv', '0022_auto_20180318_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_written', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('blurb', models.CharField(blank=True, default='', max_length=1000)),
                ('content', models.TextField(blank=True, default='')),
                ('cover', models.ImageField(upload_to='articlecovers/')),
            ],
        ),
    ]
