# Generated by Django 2.0.1 on 2018-03-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireserv', '0023_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
