# Generated by Django 2.0.1 on 2018-03-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireserv', '0024_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(blank=True, upload_to='articlecovers/'),
        ),
    ]
